kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  serviceSubnet: 10.100.0.0/16
  podSubnet: 10.244.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
