replicas: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: 26.3.3
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    memory: 2Gi

command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"

# Basic HTTP/proxy settings (chart health checks assume /auth)
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:MaxRAMPercentage=50.0
      -Djgroups.dns.query=keycloak-keycloakx-headless

# Enable dbchecker to verify DB before starting
dbchecker:
  enabled: true

# Wire to CNPG RW service with your DB/user and secret for password
database:
  vendor: postgres
  hostname: keycloak-postgres-rw.default.svc.cluster.local
  port: 5432
  username: keycloak
  database: keycloak
  existingSecret: keycloak-db-creds
  existingSecretKey: password

service:
  type: ClusterIP

ingress:
  enabled: false
