---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-keycloak-builtin-objects
spec:
  packagePullSecrets:
    - name: dockerconfigjson-github-com
  package: ghcr.io/unairada/function-keycloak-builtin-objects:dynamic-selection@sha256:44091a291c6db9205f854218b51a49cb422c95ae9a07dbf9315c2f829ccd1bdc
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-extra-resources
  annotations:
    # This tells crossplane render to connect to the function locally.
    #render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: xpkg.upbound.io/crossplane-contrib/function-extra-resources:v0.2.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.5.1

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2
