---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-keycloak-builtin-objects
spec:
  package: >-
    registry.gitlab.com/corewire/images/crossplane/function-keycloak-builtin-objects:v3.0.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-extra-resources
  annotations:
    # This tells crossplane render to connect to the function locally.
    #render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: xpkg.upbound.io/crossplane-contrib/function-extra-resources:v0.1.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.0.0-20231101225931-60aea09d94c8
